name: SASTRO
on:
  schedule:
    - cron: '9 * * * *'
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "sachienpk@gmail.com"
        git config --global user.name "sachienpk"
    - name: SASTRO
      run: |         
       wget -r https://raw.githubusercontent.com/gresketh/perma/585edbbf0df0477fb6266b359bd2d77a0f05d940/rubikcube -O youtube.m3u
       wget -r https://github.com/gresketh/unifi-tv/raw/main/alternative-playlists/unifi_1.9.15.104.m3u8 -O youtube.m3u
        
    - name: git add
      run: |
        git add -A
        ls -la
    - name: commit & push
      run: |
        git commit -m "links are updated"
        git push
